Repository Nexters/who-really-wants-to-play, pull requests merged in 2023-02, with the labels that each got.

#15 [Docs] 이슈, PR 템플릿 만들기
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/performance.md
  .github/ISSUE_TEMPLATE/setting.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📖 Docs, ⚙️ Setting

#25 feat(landing): Add basic view and animation
  .eslintrc.json
  src/App.tsx
  src/features/landing/.gitkeep
  src/features/landing/Container.tsx
  src/features/landing/components/ScrollToEnter.tsx
  src/features/landing/components/svg/BackgroundGraphicSvg.tsx
  src/style/index.scss
  src/style/landing.scss
Labels: 💇🏼‍♂️ UI/UX

#33 [Setting] stylelint auto fix
  .vscode/extensions.json
  .vscode/settings.json
  package.json
Labels: ⚙️ Setting

#34 [Fix] vscode scss setting
  .vscode/settings.json
  package.json
Labels: 🐞 Bug

#23 [Feat] Gallery 도메인 기본 작업(애니메이션 포함) 및 MasonryLayout 컴포넌트 v1
  .pnp.cjs
  .yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  package.json
  src/features/Container.tsx
  src/features/dailyBook/Container.tsx
  src/features/gallery/.gitkeep
  src/features/gallery/Container.tsx
  src/features/gallery/components/MasonryItem/index.tsx
  src/features/gallery/components/MasonryLayout/index.tsx
  src/features/gallery/constants/index.ts
  src/features/gallery/helpers/index.ts
  src/features/gallery/hooks/useMasonryLayout.ts
  src/features/gallery/hooks/useTitleAnimation.ts
  src/features/gallery/mocks/gallery.ts
  src/features/gallery/utils/getGridRowEnd.ts
  src/features/shared/components/Image/index.tsx
  src/features/shared/components/SubTitle/index.tsx
  src/features/shared/hooks/useDetectResize.ts
  src/features/shared/utils/debounce.ts
  src/features/shared/utils/throttle.ts
  src/features/types.ts
  src/style/_color.scss
  src/style/_variable.scss
  src/style/gallery.scss
  src/style/index.scss
  src/types/index.ts
  yarn.lock
Labels: 💇🏼‍♂️ UI/UX, 💻 Feature
